# Generated by Django 5.2.4 on 2025-08-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
