# Generated by Django 5.2.4 on 2025-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
