# Generated by Django 5.1.2 on 2026-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='professors/'),
        ),
    ]
