# Generated by Django 5.1.2 on 2026-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_professor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='processed_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='professors/processed/'),
        ),
    ]
