# Generated by Django 5.1.2 on 2026-08-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_professor_processed_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email_notifications_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
