# Generated by Django 6.1 on 2026-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_author_batch_testimonial_author_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
