# Generated by Django 6.1 on 2026-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_testimonial_author_email_testimonial_author_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
