# Generated by Django 5.1.2 on 2026-08-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_studentprofile_email_studentprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
